apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
  annotations:
    prometheus.io/probe: "true"
spec:
  #type: NodePort
  selector:
    name: grafana
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 3000
      #nodePort: 30032

