apiVersion: v1
kind: Service
metadata:
  labels:
    component: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  # service is created to allow prometheus to scrape endpoints
  clusterIP: None
  selector:
    component: kube-scheduler
  ports:
    - name: kube-scheduler
      protocol: TCP
      port: 10251
      targetPort: 10251
